include: package:flutter_lints/flutter.yaml

linter:
  rules:
    directives_ordering: true

    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    avoid_print: true
    always_use_package_imports: true
